#!/usr/bin/env python3
"""ETF_oos_simulation_v4.ipynb 생성 스크립트"""
import json

def code_cell(src):
    return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}

def md_cell(src):
    return {"cell_type":"markdown","metadata":{},"source":src}

C0 = md_cell([
    "# ETF OOS Pipeline v4 — Precision-80 Edition\n",
    "- **precision_hard objective**: precision < floor(0.65) → 즉시 0점, precision 최우선 최적화\n",
    "- **예측 threshold 확대**: 0.50~0.95 (step 0.02) → 더 보수적인 탐색\n",
    "- **Stage 3 신규**: Top-K 앙상블 + 검증셋 기반 threshold 자동 보정 → 목표 precision 80%\n",
    "- **타겟 후보 확대**: 0.08, 0.10 추가 → 더 선택적인 신호\n",
    "- **v3 캐시 공유**: base_dataset/VIF는 재사용, Stage 1/2/3만 새로 실행\n",
])

C1 = code_cell([
    "import yaml, warnings, os, json, gc, pickle\n",
    "from pathlib import Path\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "CONFIG_FILE = 'config_v4.yaml'\n",
    "with open(CONFIG_FILE, 'r') as f:\n",
    "    CFG = yaml.safe_load(f)\n",
    "\n",
    "EXPERIMENT_NAME    = CFG['experiment']['name']\n",
    "ETF_CODE           = CFG['etf']['code']\n",
    "START_DATE         = CFG['etf']['start_date']\n",
    "END_DATE           = CFG['etf'].get('end_date')\n",
    "BASE_DATE          = CFG['base_date']\n",
    "\n",
    "OPTUNA_VALID_MONTHS = CFG['periods']['optuna_valid_months']\n",
    "SIM_TEST_MONTHS     = CFG['periods']['sim_test_months']\n",
    "\n",
    "N_DAYS_CANDIDATES                  = CFG['target']['n_days_candidates']\n",
    "TARGET_RETURN_THRESHOLD_CANDIDATES = CFG['target']['return_threshold_candidates']\n",
    "\n",
    "VIF_THRESHOLD        = CFG['features']['vif_threshold']\n",
    "FEATURE_SELECT_YEARS = CFG['features']['feature_select_years']\n",
    "LAG_DAYS             = CFG['features']['lag_days']\n",
    "TOP_N_MAX            = CFG['features']['top_n_max']\n",
    "\n",
    "USE_RSI    = CFG['features']['use_rsi'];   RSI_PERIOD = CFG['features']['rsi_period']\n",
    "USE_MACD   = CFG['features']['use_macd'];  MACD_FAST  = CFG['features']['macd_fast']\n",
    "MACD_SLOW  = CFG['features']['macd_slow']; MACD_SIG   = CFG['features']['macd_signal']\n",
    "USE_BB     = CFG['features']['use_bollinger']\n",
    "BB_PERIOD  = CFG['features']['bollinger_period']; BB_STD = CFG['features']['bollinger_std']\n",
    "USE_ATR    = CFG['features']['use_atr'];   ATR_PERIOD = CFG['features']['atr_period']\n",
    "USE_52W    = CFG['features']['use_52w']\n",
    "\n",
    "EXTERNAL_TICKERS       = CFG['external_tickers']\n",
    "EXTERNAL_FEATURE_TYPES = CFG['external_feature_types']\n",
    "\n",
    "RANDOM_STATE = CFG['importance']['random_state']\n",
    "N_RF_RUNS    = CFG['importance']['n_rf_runs']\n",
    "N_REPEATS    = CFG['importance']['n_repeats']\n",
    "\n",
    "S1_OBJ_METRIC = CFG['stage1']['objective_metric']\n",
    "S1_MIN_EVAL   = CFG['stage1']['min_valid_eval_count']\n",
    "S1_MIN_PRED1  = CFG['stage1']['min_valid_pred_1_count']\n",
    "S1_MODEL      = CFG['stage1']['model_name']\n",
    "S1_N_EST      = CFG['stage1']['n_estimators']\n",
    "S1_TOP_N      = CFG['stage1']['top_n_fixed']\n",
    "S1_N_SEEDS    = CFG['stage1']['n_seeds']\n",
    "\n",
    "S2_N_TRIALS        = CFG['optuna_stage2']['n_trials']\n",
    "S2_OBJ_METRIC      = CFG['optuna_stage2']['objective_metric']\n",
    "S2_PRECISION_FLOOR = CFG['optuna_stage2'].get('precision_floor', 0.65)\n",
    "S2_MIN_EVAL        = CFG['optuna_stage2']['min_valid_eval_count']\n",
    "S2_MIN_PRED1       = CFG['optuna_stage2']['min_valid_pred_1_count']\n",
    "S2_MODELS          = CFG['optuna_stage2']['model_candidates']\n",
    "S2_TOP_N_RANGE     = CFG['optuna_stage2']['top_n_range']\n",
    "S2_THRESH_RANGE    = CFG['optuna_stage2']['pred_threshold_range']\n",
    "S2_THRESH_STEP     = CFG['optuna_stage2']['pred_threshold_step']\n",
    "\n",
    "S3_PRECISION_TARGET = CFG['stage3']['precision_target']\n",
    "S3_MIN_PRED         = CFG['stage3']['min_pred_count']\n",
    "S3_ENSEMBLE_TOP_K   = CFG['stage3']['ensemble_top_k']\n",
    "\n",
    "INITIAL_CASH   = CFG['simulation']['initial_cash']\n",
    "BUY_RATIO      = CFG['simulation']['buy_ratio']\n",
    "MIN_CASH_RATIO = CFG['simulation']['min_cash_ratio']\n",
    "\n",
    "LOAD_FROM_CACHE = CFG['cache']['load_from_cache']\n",
    "\n",
    "_cache_tag     = f\"{ETF_CODE}_{BASE_DATE.replace('-','')}\"\n",
    "SHARED_CACHE   = Path(f'cache_{_cache_tag}')           # v3와 공유 (base_dataset, VIF)\n",
    "V4_CACHE       = Path(f'cache_{_cache_tag}_v4')         # v4 전용 (stage1/2/3)\n",
    "SHARED_CACHE.mkdir(parents=True, exist_ok=True)\n",
    "V4_CACHE.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "OUTPUT_DIR = Path(f'experiments_v4/{EXPERIMENT_NAME}')\n",
    "OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "def save_cache(name, obj, v4_only=False):\n",
    "    d = V4_CACHE if v4_only else SHARED_CACHE\n",
    "    path = d / f'{name}.pkl'\n",
    "    with open(path, 'wb') as f: pickle.dump(obj, f)\n",
    "    print(f'[CACHE SAVED] {path}')\n",
    "\n",
    "def load_cache(name, v4_only=False):\n",
    "    for d in ([V4_CACHE] if v4_only else [SHARED_CACHE, V4_CACHE]):\n",
    "        path = d / f'{name}.pkl'\n",
    "        if path.exists():\n",
    "            with open(path, 'rb') as f: obj = pickle.load(f)\n",
    "            print(f'[CACHE LOADED] {path}')\n",
    "            return obj\n",
    "    raise FileNotFoundError(f'{name}.pkl not found')\n",
    "\n",
    "print(f'Experiment : {EXPERIMENT_NAME}')\n",
    "print(f'ETF        : {ETF_CODE}  BASE_DATE={BASE_DATE}')\n",
    "print(f'Output dir : {OUTPUT_DIR}')\n",
    "print(f'S2 objective: {S2_OBJ_METRIC}, precision_floor={S2_PRECISION_FLOOR}')\n",
    "print(f'S3 precision_target={S3_PRECISION_TARGET}, ensemble_top_k={S3_ENSEMBLE_TOP_K}')\n",
])

C2 = code_cell([
    "import numpy as np\n",
    "import pandas as pd\n",
    "import FinanceDataReader as fdr\n",
    "import optuna\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "\n",
    "from sklearn.ensemble import (\n",
    "    RandomForestClassifier, ExtraTreesClassifier,\n",
    "    GradientBoostingClassifier, HistGradientBoostingClassifier\n",
    ")\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score,\n",
    "    f1_score, roc_auc_score, confusion_matrix\n",
    ")\n",
    "from sklearn.inspection import permutation_importance\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.utils.class_weight import compute_sample_weight\n",
    "from statsmodels.stats.outliers_influence import variance_inflation_factor\n",
    "\n",
    "import xgboost as xgb\n",
    "import lightgbm as lgb\n",
    "import plotly.graph_objects as go\n",
    "from IPython.display import display\n",
    "\n",
    "def display_df(df, n=20):\n",
    "    display(df.head(n))\n",
    "\n",
    "# ── 기술지표 헬퍼 ──────────────────────────────────────────────────────────\n",
    "def _rsi(close, period=14):\n",
    "    delta = close.diff()\n",
    "    gain  = delta.clip(lower=0).rolling(period).mean()\n",
    "    loss  = (-delta.clip(upper=0)).rolling(period).mean()\n",
    "    rs    = gain / loss.replace(0, np.nan)\n",
    "    return 100 - 100 / (1 + rs)\n",
    "\n",
    "def _atr(high, low, close, period=14):\n",
    "    prev_close = close.shift(1)\n",
    "    tr = pd.concat([\n",
    "        high - low,\n",
    "        (high - prev_close).abs(),\n",
    "        (low  - prev_close).abs(),\n",
    "    ], axis=1).max(axis=1)\n",
    "    return tr.rolling(period).mean()\n",
    "\n",
    "# ── 1. 데이터 로드 ─────────────────────────────────────────────────────────\n",
    "def load_price_data(ticker, start_date='2020-01-01', end_date=None):\n",
    "    df = fdr.DataReader(ticker, start_date, end_date)\n",
    "    df = df.reset_index().rename(columns={'index': 'Date'})\n",
    "    df['Date'] = pd.to_datetime(df['Date'])\n",
    "    return df\n",
    "\n",
    "def _keep_weekdays(df, date_col='Date'):\n",
    "    df = df.copy()\n",
    "    df[date_col] = pd.to_datetime(df[date_col])\n",
    "    df = df[df[date_col].dt.weekday < 5].sort_values(date_col).reset_index(drop=True)\n",
    "    return df\n",
    "\n",
    "# ── 2. ETF 피처 생성 ───────────────────────────────────────────────────────\n",
    "def make_target_etf_features(etf_df, prefix, cfg=None):\n",
    "    df    = etf_df.copy().sort_values('Date').reset_index(drop=True)\n",
    "    close = df['Adj Close']\n",
    "    high  = df['High']   if 'High'   in df.columns else close\n",
    "    low   = df['Low']    if 'Low'    in df.columns else close\n",
    "    volume= df['Volume']\n",
    "\n",
    "    r = pd.DataFrame()\n",
    "    r['Date']                       = df['Date']\n",
    "    r[f'{prefix}_adj_close']        = close\n",
    "    r[f'{prefix}_ret_1d']           = close.pct_change(1)\n",
    "    r[f'{prefix}_ret_5d']           = close.pct_change(5)\n",
    "    r[f'{prefix}_ret_20d']          = close.pct_change(20)\n",
    "\n",
    "    ma5  = close.rolling(5).mean()\n",
    "    ma20 = close.rolling(20).mean()\n",
    "    ma60 = close.rolling(60).mean()\n",
    "    ma200= close.rolling(200).mean()\n",
    "    r[f'{prefix}_ma5_ratio']        = close / ma5  - 1\n",
    "    r[f'{prefix}_ma20_ratio']       = close / ma20 - 1\n",
    "    r[f'{prefix}_ma60_ratio']       = close / ma60 - 1\n",
    "    r[f'{prefix}_ma200_ratio']      = close / ma200 - 1\n",
    "    r[f'{prefix}_ma5_ma20_ratio']   = ma5 / ma20 - 1\n",
    "    r[f'{prefix}_ma20_ma60_ratio']  = ma20 / ma60 - 1\n",
    "\n",
    "    r[f'{prefix}_vol_20d']          = r[f'{prefix}_ret_1d'].rolling(20).std()\n",
    "    r[f'{prefix}_vol_5d']           = r[f'{prefix}_ret_1d'].rolling(5).std()\n",
    "\n",
    "    vol_ma20 = volume.rolling(20).mean()\n",
    "    r[f'{prefix}_volume_ratio_20d'] = volume / vol_ma20 - 1\n",
    "    r[f'{prefix}_volume_ratio_5d']  = volume / volume.rolling(5).mean() - 1\n",
    "\n",
    "    # 연속 상승/하락 일수\n",
    "    up = (close.diff() > 0).astype(int)\n",
    "    consec = up.groupby((up != up.shift()).cumsum()).cumcount() + 1\n",
    "    r[f'{prefix}_consec_up']   = np.where(up == 1,  consec, 0)\n",
    "    r[f'{prefix}_consec_down'] = np.where(up == 0, -consec, 0)\n",
    "\n",
    "    # 고가/저가 대비 위치 (10/20일)\n",
    "    r[f'{prefix}_hl_pos_10d'] = (close - low.rolling(10).min()) / \\\n",
    "                                 (high.rolling(10).max() - low.rolling(10).min() + 1e-9)\n",
    "    r[f'{prefix}_hl_pos_20d'] = (close - low.rolling(20).min()) / \\\n",
    "                                 (high.rolling(20).max() - low.rolling(20).min() + 1e-9)\n",
    "\n",
    "    if cfg is None or cfg.get('use_rsi', True):\n",
    "        p = (cfg or {}).get('rsi_period', 14)\n",
    "        r[f'{prefix}_rsi_{p}'] = _rsi(close, p)\n",
    "\n",
    "    if cfg is None or cfg.get('use_macd', True):\n",
    "        fast = (cfg or {}).get('macd_fast', 12)\n",
    "        slow = (cfg or {}).get('macd_slow', 26)\n",
    "        sig  = (cfg or {}).get('macd_signal', 9)\n",
    "        ema_f = close.ewm(span=fast, adjust=False).mean()\n",
    "        ema_s = close.ewm(span=slow, adjust=False).mean()\n",
    "        macd  = ema_f - ema_s\n",
    "        macd_sig = macd.ewm(span=sig, adjust=False).mean()\n",
    "        r[f'{prefix}_macd']        = macd\n",
    "        r[f'{prefix}_macd_hist']   = macd - macd_sig\n",
    "        r[f'{prefix}_macd_signal'] = macd_sig\n",
    "\n",
    "    if cfg is None or cfg.get('use_bollinger', True):\n",
    "        p   = (cfg or {}).get('bollinger_period', 20)\n",
    "        std = (cfg or {}).get('bollinger_std', 2.0)\n",
    "        ma  = close.rolling(p).mean()\n",
    "        sd  = close.rolling(p).std()\n",
    "        upper = ma + std * sd\n",
    "        lower = ma - std * sd\n",
    "        band  = (upper - lower).replace(0, np.nan)\n",
    "        r[f'{prefix}_bb_pct']   = (close - lower) / band\n",
    "        r[f'{prefix}_bb_width'] = band / ma\n",
    "\n",
    "    if cfg is None or cfg.get('use_atr', True):\n",
    "        p = (cfg or {}).get('atr_period', 14)\n",
    "        atr_val = _atr(high, low, close, p)\n",
    "        r[f'{prefix}_atr_{p}']       = atr_val\n",
    "        r[f'{prefix}_atr_{p}_ratio'] = atr_val / close\n",
    "\n",
    "    if cfg is None or cfg.get('use_52w', True):\n",
    "        r[f'{prefix}_52w_high_ratio'] = close / close.rolling(252).max() - 1\n",
    "        r[f'{prefix}_52w_low_ratio']  = close / close.rolling(252).min() - 1\n",
    "\n",
    "    return r\n",
    "\n",
    "# ── 3. 외부지표 피처 ───────────────────────────────────────────────────────\n",
    "def make_external_features(raw_df, name, feature_type='price'):\n",
    "    df    = raw_df.copy().sort_values('Date').reset_index(drop=True)\n",
    "    close = df['Adj Close']\n",
    "    r     = pd.DataFrame()\n",
    "    r['Date'] = df['Date']\n",
    "\n",
    "    if feature_type == 'price':\n",
    "        r[f'{name}_ret_5d']  = close.pct_change(5)\n",
    "        r[f'{name}_ret_20d'] = close.pct_change(20)\n",
    "    elif feature_type == 'risk':\n",
    "        r[f'{name}_level']   = close\n",
    "        r[f'{name}_chg_5d']  = close.diff(5)\n",
    "        r[f'{name}_chg_20d'] = close.diff(20)\n",
    "    elif feature_type == 'rate':\n",
    "        r[f'{name}_level']   = close\n",
    "        r[f'{name}_diff_5d'] = close.diff(5)\n",
    "        r[f'{name}_diff_20d']= close.diff(20)\n",
    "    else:\n",
    "        raise ValueError(f'Unknown feature_type: {feature_type}')\n",
    "    return r\n",
    "\n",
    "# ── 4. Base Feature Dataset ────────────────────────────────────────────────\n",
    "def make_base_feature_dataset(etf_code, external_tickers, external_feature_types,\n",
    "                               start_date='2020-01-01', end_date=None, feat_cfg=None):\n",
    "    etf_raw = _keep_weekdays(load_price_data(etf_code, start_date, end_date))\n",
    "    base_df = make_target_etf_features(etf_raw, prefix=etf_code, cfg=feat_cfg)\n",
    "    base_df = _keep_weekdays(base_df)\n",
    "\n",
    "    for name, ticker in external_tickers.items():\n",
    "        print(f'  Loading {name} ({ticker})')\n",
    "        try:\n",
    "            raw   = _keep_weekdays(load_price_data(ticker, start_date, end_date))\n",
    "            ftype = external_feature_types.get(name, 'price')\n",
    "            ext   = _keep_weekdays(make_external_features(raw, name, ftype))\n",
    "            base_df = base_df.merge(ext, on='Date', how='left')\n",
    "        except Exception as e:\n",
    "            print(f'  [SKIP] {name}: {e}')\n",
    "\n",
    "    base_df = _keep_weekdays(base_df)\n",
    "    etf_prefix    = f'{etf_code}_'\n",
    "    external_cols = [c for c in base_df.columns if c != 'Date' and not c.startswith(etf_prefix)]\n",
    "    base_df[external_cols] = base_df[external_cols].ffill()\n",
    "\n",
    "    close_col    = f'{etf_code}_adj_close'\n",
    "    feature_cols = [c for c in base_df.columns if c not in ['Date', close_col]]\n",
    "    return base_df, feature_cols, close_col\n",
    "\n",
    "# ── 5. VIF 제거 ────────────────────────────────────────────────────────────\n",
    "def reduce_features_by_vif(df, feature_cols, vif_threshold=30.0, verbose=True):\n",
    "    numeric_cols = [c for c in feature_cols if c in df.columns and pd.api.types.is_numeric_dtype(df[c])]\n",
    "    work = df[numeric_cols].replace([np.inf, -np.inf], np.nan).dropna(axis=0).copy()\n",
    "    nunique   = work.nunique()\n",
    "    remaining = [c for c in numeric_cols if nunique.get(c, 0) > 1]\n",
    "    removed   = []\n",
    "\n",
    "    while True:\n",
    "        if len(remaining) <= 1: break\n",
    "        X  = work[remaining].copy()\n",
    "        sc = StandardScaler()\n",
    "        Xs = sc.fit_transform(X)\n",
    "        vifs = []\n",
    "        for i, col in enumerate(remaining):\n",
    "            try:    v = variance_inflation_factor(Xs, i)\n",
    "            except: v = np.inf\n",
    "            vifs.append((col, v))\n",
    "        worst_col, worst_v = max(vifs, key=lambda x: x[1])\n",
    "        if verbose: print(f'  VIF max: {worst_v:.1f}  ({worst_col})')\n",
    "        if worst_v <= vif_threshold: break\n",
    "        remaining.remove(worst_col)\n",
    "        removed.append({'removed_feature': worst_col, 'vif': worst_v})\n",
    "\n",
    "    print(f'  VIF 제거: {len(removed)}개 / 남은 피처: {len(remaining)}개')\n",
    "    return remaining, pd.DataFrame(removed)\n",
    "\n",
    "# ── 6. Target 생성 ─────────────────────────────────────────────────────────\n",
    "def add_target_column(df, close_col, n_days=5, threshold=0.05, target_col=None):\n",
    "    r = df.copy().sort_values('Date').reset_index(drop=True)\n",
    "    if target_col is None:\n",
    "        target_col = f'target_{n_days}d_up_{int(threshold*100)}pct'\n",
    "    future_close = r[close_col].shift(-n_days)\n",
    "    r[f'future_ret_{n_days}d'] = future_close / r[close_col] - 1\n",
    "    r[target_col] = np.where(r[f'future_ret_{n_days}d'] >= threshold, 1, 0)\n",
    "    r.loc[r[f'future_ret_{n_days}d'].isna(), target_col] = np.nan\n",
    "    return r, target_col\n",
    "\n",
    "# ── 7. Lag 탐색 & 적용 ────────────────────────────────────────────────────\n",
    "def find_best_lag_by_feature(df, feature_cols, target_col, lag_days, date_col='Date'):\n",
    "    records = []\n",
    "    for col in feature_cols:\n",
    "        if col not in df.columns: continue\n",
    "        for lag in lag_days:\n",
    "            tmp = df[[date_col, col, target_col]].copy()\n",
    "            tmp[f'{col}_lag{lag}'] = tmp[col].shift(lag)\n",
    "            tmp = tmp[[f'{col}_lag{lag}', target_col]].replace([np.inf,-np.inf], np.nan).dropna()\n",
    "            if len(tmp) < 30: continue\n",
    "            x    = tmp[f'{col}_lag{lag}']\n",
    "            corr = x.corr(tmp[target_col]) if x.nunique() > 1 else np.nan\n",
    "            records.append({'feature': col, 'lag': lag, 'corr': corr,\n",
    "                            'abs_corr': abs(corr) if pd.notna(corr) else np.nan})\n",
    "    lag_df = pd.DataFrame(records)\n",
    "    if lag_df.empty: raise ValueError('lag 탐색 결과 없음')\n",
    "    best_lag_df = (lag_df.sort_values(['feature','abs_corr'], ascending=[True,False])\n",
    "                         .groupby('feature', as_index=False).head(1)\n",
    "                         .sort_values('abs_corr', ascending=False).reset_index(drop=True))\n",
    "    return lag_df, best_lag_df\n",
    "\n",
    "def make_lagged_dataset(df, best_lag_df, target_col=None, close_col=None,\n",
    "                        n_days=5, date_col='Date', drop_target_na=True):\n",
    "    r = pd.DataFrame()\n",
    "    r[date_col] = df[date_col]\n",
    "    if close_col and close_col in df.columns:\n",
    "        r[close_col] = df[close_col]\n",
    "    fut = f'future_ret_{n_days}d'\n",
    "    if fut in df.columns: r[fut] = df[fut]\n",
    "    if target_col and target_col in df.columns: r[target_col] = df[target_col]\n",
    "\n",
    "    lagged_cols = []\n",
    "    for _, row in best_lag_df.iterrows():\n",
    "        feat = row['feature']; lag = int(row['lag'])\n",
    "        if feat not in df.columns: continue\n",
    "        lc = f'{feat}_lag{lag}'\n",
    "        r[lc] = df[feat].shift(lag)\n",
    "        lagged_cols.append(lc)\n",
    "\n",
    "    r = r.replace([np.inf, -np.inf], np.nan)\n",
    "    if drop_target_na and target_col and target_col in r.columns:\n",
    "        r = r.dropna(subset=[target_col] + lagged_cols).reset_index(drop=True)\n",
    "    else:\n",
    "        r = r.reset_index(drop=True)\n",
    "    return r, lagged_cols\n",
    "\n",
    "# ── 8. Permutation Importance ─────────────────────────────────────────────\n",
    "def run_permutation_importance(lagged_df, feature_cols, target_col,\n",
    "                                n_rf_runs=3, n_repeats=5, random_state=42):\n",
    "    df  = lagged_df.copy()\n",
    "    X   = df[feature_cols].replace([np.inf,-np.inf], np.nan)\n",
    "    tmp = pd.concat([X, df[target_col]], axis=1).dropna().copy()\n",
    "    X   = tmp[feature_cols].copy()\n",
    "    y   = tmp[target_col].astype(int)\n",
    "\n",
    "    all_imp = []\n",
    "    for run in range(n_rf_runs):\n",
    "        rf = RandomForestClassifier(n_estimators=300, class_weight='balanced',\n",
    "                                    random_state=random_state+run, n_jobs=-1)\n",
    "        rf.fit(X, y)\n",
    "        pi = permutation_importance(rf, X, y, n_repeats=n_repeats,\n",
    "                                    random_state=random_state+run, n_jobs=-1)\n",
    "        for fi, col in enumerate(feature_cols):\n",
    "            for val in pi.importances[fi]:\n",
    "                all_imp.append({'feature': col, 'importance': val})\n",
    "\n",
    "    imp_df = pd.DataFrame(all_imp)\n",
    "    agg = (imp_df.groupby('feature')['importance']\n",
    "                 .agg(mean_importance='mean', std_importance='std')\n",
    "                 .reset_index()\n",
    "                 .sort_values('mean_importance', ascending=False)\n",
    "                 .reset_index(drop=True))\n",
    "    agg['score'] = agg['mean_importance'] - agg['std_importance'].fillna(0)\n",
    "    return agg\n",
    "\n",
    "# ── 9. 지표 계산 ───────────────────────────────────────────────────────────\n",
    "def safe_binary_metrics(y_true, pred, pred_proba=None):\n",
    "    y_true = pd.Series(y_true).astype(int)\n",
    "    pred   = pd.Series(pred).astype(int)\n",
    "    out = {\n",
    "        'eval_count':     int(len(y_true)),\n",
    "        'actual_1_count': int((y_true==1).sum()),\n",
    "        'pred_1_count':   int((pred==1).sum()),\n",
    "        'accuracy':       accuracy_score(y_true, pred) if len(y_true) else np.nan,\n",
    "        'precision':      precision_score(y_true, pred, zero_division=0),\n",
    "        'recall':         recall_score(y_true, pred, zero_division=0),\n",
    "        'f1':             f1_score(y_true, pred, zero_division=0),\n",
    "    }\n",
    "    if pred_proba is not None and len(y_true) > 0 and y_true.nunique() == 2:\n",
    "        try: out['roc_auc'] = roc_auc_score(y_true, pred_proba)\n",
    "        except: out['roc_auc'] = np.nan\n",
    "    return out\n",
    "\n",
    "# ── 10. 모델 생성 ──────────────────────────────────────────────────────────\n",
    "def make_classifier(model_name, random_state=42, model_params=None,\n",
    "                    pos_count=None, neg_count=None):\n",
    "    p = model_params or {}\n",
    "\n",
    "    if model_name == 'random_forest':\n",
    "        return RandomForestClassifier(\n",
    "            n_estimators=p.get('n_estimators', 500),\n",
    "            max_depth=p.get('max_depth', None),\n",
    "            min_samples_split=p.get('min_samples_split', 2),\n",
    "            min_samples_leaf=p.get('min_samples_leaf', 1),\n",
    "            max_features=p.get('max_features', 'sqrt'),\n",
    "            class_weight=p.get('class_weight', 'balanced'),\n",
    "            random_state=random_state, n_jobs=-1)\n",
    "\n",
    "    if model_name == 'extra_trees':\n",
    "        return ExtraTreesClassifier(\n",
    "            n_estimators=p.get('n_estimators', 500),\n",
    "            max_depth=p.get('max_depth', None),\n",
    "            min_samples_split=p.get('min_samples_split', 2),\n",
    "            min_samples_leaf=p.get('min_samples_leaf', 1),\n",
    "            max_features=p.get('max_features', 'sqrt'),\n",
    "            class_weight=p.get('class_weight', 'balanced'),\n",
    "            random_state=random_state, n_jobs=-1)\n",
    "\n",
    "    if model_name == 'hist_gradient_boosting':\n",
    "        return HistGradientBoostingClassifier(\n",
    "            max_iter=p.get('max_iter', 300),\n",
    "            learning_rate=p.get('learning_rate', 0.05),\n",
    "            max_leaf_nodes=p.get('max_leaf_nodes', 31),\n",
    "            min_samples_leaf=p.get('min_samples_leaf', 20),\n",
    "            class_weight='balanced',\n",
    "            random_state=random_state)\n",
    "\n",
    "    if model_name == 'xgboost':\n",
    "        scale_pw = (neg_count / pos_count) if (pos_count and neg_count and pos_count > 0) else 1.0\n",
    "        return xgb.XGBClassifier(\n",
    "            n_estimators=p.get('n_estimators', 300),\n",
    "            learning_rate=p.get('learning_rate', 0.05),\n",
    "            max_depth=p.get('max_depth', 4),\n",
    "            subsample=p.get('subsample', 0.8),\n",
    "            colsample_bytree=p.get('colsample_bytree', 0.8),\n",
    "            scale_pos_weight=scale_pw,\n",
    "            random_state=random_state, eval_metric='logloss', verbosity=0, n_jobs=-1)\n",
    "\n",
    "    if model_name == 'lightgbm':\n",
    "        return lgb.LGBMClassifier(\n",
    "            n_estimators=p.get('n_estimators', 300),\n",
    "            learning_rate=p.get('learning_rate', 0.05),\n",
    "            max_depth=p.get('max_depth', -1),\n",
    "            num_leaves=p.get('num_leaves', 31),\n",
    "            subsample=p.get('subsample', 0.8),\n",
    "            colsample_bytree=p.get('colsample_bytree', 0.8),\n",
    "            is_unbalance=True,\n",
    "            random_state=random_state, verbose=-1, n_jobs=-1)\n",
    "\n",
    "    raise ValueError(f'Unknown model: {model_name}')\n",
    "\n",
    "def suggest_model_params(trial, model_name):\n",
    "    if model_name in ['random_forest', 'extra_trees']:\n",
    "        return {\n",
    "            'n_estimators':      trial.suggest_int(f'{model_name}_n_est', 200, 800, step=100),\n",
    "            'max_depth':         trial.suggest_categorical(f'{model_name}_max_depth', [None,3,5,7,10]),\n",
    "            'min_samples_split': trial.suggest_int(f'{model_name}_mss', 2, 10),\n",
    "            'min_samples_leaf':  trial.suggest_int(f'{model_name}_msl', 1, 10),\n",
    "            'max_features':      trial.suggest_categorical(f'{model_name}_mf', ['sqrt','log2']),\n",
    "            'class_weight':      trial.suggest_categorical(f'{model_name}_cw',\n",
    "                                     ['balanced','balanced_subsample']),\n",
    "        }\n",
    "    if model_name == 'hist_gradient_boosting':\n",
    "        return {\n",
    "            'max_iter':        trial.suggest_int('hgb_iter', 100, 500, step=100),\n",
    "            'learning_rate':   trial.suggest_float('hgb_lr', 0.01, 0.2, log=True),\n",
    "            'max_leaf_nodes':  trial.suggest_int('hgb_leaves', 15, 63),\n",
    "            'min_samples_leaf':trial.suggest_int('hgb_msl', 10, 50),\n",
    "        }\n",
    "    if model_name == 'xgboost':\n",
    "        return {\n",
    "            'n_estimators':    trial.suggest_int('xgb_n_est', 100, 600, step=100),\n",
    "            'learning_rate':   trial.suggest_float('xgb_lr', 0.01, 0.2, log=True),\n",
    "            'max_depth':       trial.suggest_int('xgb_depth', 3, 8),\n",
    "            'subsample':       trial.suggest_float('xgb_sub', 0.6, 1.0, step=0.1),\n",
    "            'colsample_bytree':trial.suggest_float('xgb_col', 0.6, 1.0, step=0.1),\n",
    "        }\n",
    "    if model_name == 'lightgbm':\n",
    "        return {\n",
    "            'n_estimators':    trial.suggest_int('lgb_n_est', 100, 600, step=100),\n",
    "            'learning_rate':   trial.suggest_float('lgb_lr', 0.01, 0.2, log=True),\n",
    "            'num_leaves':      trial.suggest_int('lgb_leaves', 15, 127),\n",
    "            'subsample':       trial.suggest_float('lgb_sub', 0.6, 1.0, step=0.1),\n",
    "            'colsample_bytree':trial.suggest_float('lgb_col', 0.6, 1.0, step=0.1),\n",
    "        }\n",
    "    raise ValueError(model_name)\n",
    "\n",
    "def evaluate_model_on_period(train_df, eval_df, feature_cols, target_col, close_col,\n",
    "                              n_days, model_name, model_params, pred_threshold,\n",
    "                              random_state=42):\n",
    "    keep_train = [target_col] + feature_cols\n",
    "    tr = train_df[keep_train].replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "    keep_eval  = ['Date', target_col, f'future_ret_{n_days}d', close_col] + feature_cols\n",
    "    ev = eval_df[[c for c in keep_eval if c in eval_df.columns]].replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "\n",
    "    if len(tr) == 0 or len(ev) == 0:\n",
    "        raise ValueError('train/eval 비어있음')\n",
    "    if tr[target_col].nunique() < 2:\n",
    "        raise ValueError('train target 단일 class')\n",
    "\n",
    "    X_tr = tr[feature_cols]; y_tr = tr[target_col].astype(int)\n",
    "    X_ev = ev[feature_cols]; y_ev = ev[target_col].astype(int)\n",
    "\n",
    "    pos = int((y_tr==1).sum()); neg = int((y_tr==0).sum())\n",
    "    model = make_classifier(model_name, random_state=random_state,\n",
    "                            model_params=model_params, pos_count=pos, neg_count=neg)\n",
    "    model.fit(X_tr, y_tr)\n",
    "\n",
    "    pred_proba = model.predict_proba(X_ev)[:,1] if hasattr(model,'predict_proba') \\\n",
    "                 else model.predict(X_ev).astype(float)\n",
    "    pred       = (pred_proba >= pred_threshold).astype(int)\n",
    "    metrics    = safe_binary_metrics(y_ev, pred, pred_proba)\n",
    "\n",
    "    pred_df = ev[['Date', close_col, f'future_ret_{n_days}d', target_col]].copy()\n",
    "    pred_df['pred_proba'] = pred_proba\n",
    "    pred_df['pred']       = pred\n",
    "    return model, metrics, pred_df\n",
    "\n",
    "# ── 11. Objective Score ───────────────────────────────────────────────────\n",
    "def compute_objective_score(metrics, pred_df, objective_metric, n_days,\n",
    "                             min_eval=30, min_pred1=3, precision_floor=0.65):\n",
    "    ec   = int(metrics.get('eval_count',0) or 0)\n",
    "    a1   = int(metrics.get('actual_1_count',0) or 0)\n",
    "    p1   = int(metrics.get('pred_1_count',0) or 0)\n",
    "    if ec < min_eval or p1 < min_pred1: return 0.0\n",
    "\n",
    "    pos_rate  = a1 / ec\n",
    "    precision = float(metrics.get('precision',0) or 0)\n",
    "    recall    = float(metrics.get('recall',0) or 0)\n",
    "    f1        = float(metrics.get('f1',0) or 0)\n",
    "    pl        = max(0.0, precision - pos_rate)\n",
    "    fl        = max(0.0, f1 - pos_rate)\n",
    "\n",
    "    if objective_metric == 'precision_lift_recall': return pl * recall\n",
    "    if objective_metric == 'precision_lift':        return pl\n",
    "    if objective_metric == 'f1_lift':               return fl\n",
    "    if objective_metric == 'return_score':\n",
    "        strat = np.where(pred_df['pred']==1, pred_df[f'future_ret_{n_days}d'], 0.0)\n",
    "        cret  = float(np.prod(1 + strat) - 1)\n",
    "        return cret + 0.5 * pl * recall\n",
    "\n",
    "    # ★ v4 신규: precision_hard\n",
    "    # precision < floor면 즉시 0 반환 → Optuna가 보수적 영역을 집중 탐색\n",
    "    if objective_metric == 'precision_hard':\n",
    "        if precision < precision_floor: return 0.0\n",
    "        # precision 최우선, recall은 소폭 보너스, 예측 건수도 로그 보너스\n",
    "        return precision * (1 + 0.3 * recall) * np.log1p(p1)\n",
    "\n",
    "    raise ValueError(objective_metric)\n",
    "\n",
    "def _metrics_extra(metrics, n_days, pred_df=None):\n",
    "    ec = int(metrics.get('eval_count',0) or 0)\n",
    "    a1 = int(metrics.get('actual_1_count',0) or 0)\n",
    "    pos_rate  = a1 / ec if ec > 0 else np.nan\n",
    "    precision = float(metrics.get('precision',0) or 0)\n",
    "    recall    = float(metrics.get('recall',0) or 0)\n",
    "    f1        = float(metrics.get('f1',0) or 0)\n",
    "    p1        = int(metrics.get('pred_1_count',0) or 0)\n",
    "    return {\n",
    "        'positive_rate':         pos_rate,\n",
    "        'precision_lift':        precision - pos_rate if pd.notna(pos_rate) else np.nan,\n",
    "        'f1_lift':               f1 - pos_rate        if pd.notna(pos_rate) else np.nan,\n",
    "        'precision_lift_recall': max(0, precision-pos_rate)*recall if pd.notna(pos_rate) else np.nan,\n",
    "        'pred_1_ratio':          p1/ec if ec > 0 else np.nan,\n",
    "    }\n",
    "\n",
    "print('공통 함수 로드 완료')\n",
])

C3 = code_cell([
    "def make_oos_windows(base_date, start_date, optuna_valid_months, sim_test_months):\n",
    "    base  = pd.to_datetime(base_date)\n",
    "    start = pd.to_datetime(start_date)\n",
    "    base_p= base.to_period('M')\n",
    "\n",
    "    sim_start_p   = base_p  - (sim_test_months - 1)\n",
    "    valid_end_p   = sim_start_p - 1\n",
    "    valid_start_p = valid_end_p - (optuna_valid_months - 1)\n",
    "    train_end_p   = valid_start_p - 1\n",
    "\n",
    "    return {\n",
    "        'train_start':        start,\n",
    "        'train_end':          train_end_p.to_timestamp(how='end').normalize(),\n",
    "        'optuna_valid_start': valid_start_p.to_timestamp(how='start'),\n",
    "        'optuna_valid_end':   valid_end_p.to_timestamp(how='end').normalize(),\n",
    "        'sim_test_start':     sim_start_p.to_timestamp(how='start'),\n",
    "        'sim_test_end':       base,\n",
    "        'base_date':          base,\n",
    "    }\n",
    "\n",
    "WINDOWS = make_oos_windows(BASE_DATE, START_DATE, OPTUNA_VALID_MONTHS, SIM_TEST_MONTHS)\n",
    "for k, v in WINDOWS.items():\n",
    "    print(f'  {k:22s}: {str(v)[:10]}')\n",
])

C4 = code_cell([
    "feat_cfg = {\n",
    "    'use_rsi': USE_RSI, 'rsi_period': RSI_PERIOD,\n",
    "    'use_macd': USE_MACD, 'macd_fast': MACD_FAST, 'macd_slow': MACD_SLOW, 'macd_signal': MACD_SIG,\n",
    "    'use_bollinger': USE_BB, 'bollinger_period': BB_PERIOD, 'bollinger_std': BB_STD,\n",
    "    'use_atr': USE_ATR, 'atr_period': ATR_PERIOD,\n",
    "    'use_52w': USE_52W,\n",
    "}\n",
    "\n",
    "if LOAD_FROM_CACHE:\n",
    "    try:\n",
    "        base_df, raw_feature_cols, close_col = load_cache('base_dataset')\n",
    "    except FileNotFoundError:\n",
    "        print('캐시 없음, 새로 생성...')\n",
    "        base_df, raw_feature_cols, close_col = make_base_feature_dataset(\n",
    "            etf_code=ETF_CODE, external_tickers=EXTERNAL_TICKERS,\n",
    "            external_feature_types=EXTERNAL_FEATURE_TYPES,\n",
    "            start_date=START_DATE, end_date=END_DATE, feat_cfg=feat_cfg)\n",
    "        save_cache('base_dataset', (base_df, raw_feature_cols, close_col))\n",
    "else:\n",
    "    print('Base feature dataset 생성 중...')\n",
    "    base_df, raw_feature_cols, close_col = make_base_feature_dataset(\n",
    "        etf_code=ETF_CODE, external_tickers=EXTERNAL_TICKERS,\n",
    "        external_feature_types=EXTERNAL_FEATURE_TYPES,\n",
    "        start_date=START_DATE, end_date=END_DATE, feat_cfg=feat_cfg)\n",
    "    save_cache('base_dataset', (base_df, raw_feature_cols, close_col))\n",
    "\n",
    "print(f'\\nbase_df shape: {base_df.shape}')\n",
    "print(f'피처 수: {len(raw_feature_cols)}')\n",
    "print(f'기간: {base_df[\"Date\"].min().date()} ~ {base_df[\"Date\"].max().date()}')\n",
])

C5 = code_cell([
    "_vif_pkl = SHARED_CACHE / 'vif_feature_cols.pkl'\n",
    "if LOAD_FROM_CACHE and _vif_pkl.exists():\n",
    "    vif_feature_cols = load_cache('vif_feature_cols')\n",
    "else:\n",
    "    train_base_df = base_df[\n",
    "        (base_df['Date'] >= WINDOWS['train_start']) &\n",
    "        (base_df['Date'] <= WINDOWS['train_end'])\n",
    "    ].copy()\n",
    "    print(f'VIF 계산 대상: {train_base_df.shape}')\n",
    "    vif_feature_cols, removed_vif_df = reduce_features_by_vif(\n",
    "        df=train_base_df, feature_cols=raw_feature_cols, vif_threshold=VIF_THRESHOLD)\n",
    "    save_cache('vif_feature_cols', vif_feature_cols)\n",
    "\n",
    "print(f'VIF 통과 피처: {len(vif_feature_cols)}개')\n",
])

C6 = code_cell([
    "feature_cache = {}\n",
    "if LOAD_FROM_CACHE:\n",
    "    try:\n",
    "        feature_cache = load_cache('feature_cache')\n",
    "        print(f'feature_cache 로드: {len(feature_cache)}가지 조합')\n",
    "    except FileNotFoundError:\n",
    "        print('feature_cache 없음, 새로 생성')\n",
    "\n",
    "def _gc(msg):\n",
    "    gc.collect()\n",
    "    print(f'  [GC] {msg}')\n",
    "\n",
    "def build_feature_artifacts(n_days, target_return_threshold, include_infer_df=False):\n",
    "    key = (int(n_days), float(target_return_threshold))\n",
    "    if key in feature_cache:\n",
    "        art = feature_cache[key]\n",
    "        if include_infer_df and 'all_lagged_infer_df' not in art:\n",
    "            td, _ = add_target_column(base_df, close_col, n_days, target_return_threshold)\n",
    "            art['all_lagged_infer_df'], _ = make_lagged_dataset(\n",
    "                td, art['best_lag_df'], target_col=art['target_col'],\n",
    "                close_col=close_col, n_days=n_days, drop_target_na=False)\n",
    "            del td; _gc('infer target_df deleted')\n",
    "        return art\n",
    "\n",
    "    print(f'  [build] n_days={n_days}, threshold={target_return_threshold}')\n",
    "\n",
    "    target_df, target_col = add_target_column(base_df, close_col, n_days, target_return_threshold)\n",
    "\n",
    "    fs_end   = WINDOWS['train_end']\n",
    "    fs_start = fs_end - pd.DateOffset(years=FEATURE_SELECT_YEARS)\n",
    "    fs_df    = target_df[(target_df['Date']>=fs_start)&(target_df['Date']<=fs_end)].copy()\n",
    "    print(f'    feature select 기간: {fs_df[\"Date\"].min().date()} ~ {fs_df[\"Date\"].max().date()}')\n",
    "\n",
    "    _, best_lag_df = find_best_lag_by_feature(fs_df, vif_feature_cols, target_col, LAG_DAYS)\n",
    "    del fs_df; _gc('fs_df deleted')\n",
    "\n",
    "    all_lagged_eval_df, lagged_cols = make_lagged_dataset(\n",
    "        target_df, best_lag_df, target_col=target_col,\n",
    "        close_col=close_col, n_days=n_days, drop_target_na=True)\n",
    "\n",
    "    fs_lag_df = all_lagged_eval_df[\n",
    "        (all_lagged_eval_df['Date']>=fs_start)&(all_lagged_eval_df['Date']<=fs_end)].copy()\n",
    "\n",
    "    if fs_lag_df[target_col].nunique() < 2:\n",
    "        raise ValueError('Feature selection target 단일 class')\n",
    "\n",
    "    imp_df = run_permutation_importance(\n",
    "        fs_lag_df, lagged_cols, target_col, N_RF_RUNS, N_REPEATS, RANDOM_STATE)\n",
    "\n",
    "    top_cols_max = imp_df['feature'].head(TOP_N_MAX).tolist()\n",
    "\n",
    "    art = {\n",
    "        'n_days': int(n_days), 'target_return_threshold': target_return_threshold,\n",
    "        'target_col': target_col, 'best_lag_df': best_lag_df,\n",
    "        'all_lagged_eval_df': all_lagged_eval_df, 'lagged_feature_cols': lagged_cols,\n",
    "        'importance_df': imp_df, 'top_feature_cols_max': top_cols_max,\n",
    "    }\n",
    "    if include_infer_df:\n",
    "        art['all_lagged_infer_df'], _ = make_lagged_dataset(\n",
    "            target_df, best_lag_df, target_col=target_col,\n",
    "            close_col=close_col, n_days=n_days, drop_target_na=False)\n",
    "\n",
    "    feature_cache[key] = art\n",
    "    del target_df, fs_lag_df; _gc(f'deleted after build n_days={n_days} th={target_return_threshold}')\n",
    "    return art\n",
    "\n",
    "print('Feature cache 함수 준비 완료')\n",
])

C7 = code_cell([
    "def run_stage1_grid_search(objective_metric, n_seeds=3, random_state=42):\n",
    "    from itertools import product\n",
    "    rows   = []\n",
    "    combos = list(product(N_DAYS_CANDIDATES, TARGET_RETURN_THRESHOLD_CANDIDATES))\n",
    "    print(f'총 {len(combos)}가지 조합 x {n_seeds} seeds = {len(combos)*n_seeds}회 평가')\n",
    "\n",
    "    for i, (n_days, threshold) in enumerate(combos):\n",
    "        print(f'  [{i+1}/{len(combos)}] n_days={n_days}, threshold={threshold}', end=' ')\n",
    "        seed_scores = []\n",
    "        try:\n",
    "            art = build_feature_artifacts(n_days, threshold)\n",
    "            tc  = art['target_col']\n",
    "            ev  = art['all_lagged_eval_df']\n",
    "            fc  = art['top_feature_cols_max'][:S1_TOP_N]\n",
    "\n",
    "            if not fc:\n",
    "                print('→ 피처 없음 skip'); continue\n",
    "\n",
    "            tr_df = ev[(ev['Date']>=WINDOWS['train_start'])&(ev['Date']<=WINDOWS['train_end'])]\n",
    "            va_df = ev[(ev['Date']>=WINDOWS['optuna_valid_start'])&(ev['Date']<=WINDOWS['optuna_valid_end'])]\n",
    "            params = {'n_estimators': S1_N_EST, 'class_weight': 'balanced'}\n",
    "\n",
    "            for s in range(n_seeds):\n",
    "                _, metrics, pred_df = evaluate_model_on_period(\n",
    "                    tr_df, va_df, fc, tc, close_col, n_days,\n",
    "                    S1_MODEL, params, pred_threshold=0.5, random_state=random_state+s*100)\n",
    "                score = compute_objective_score(metrics, pred_df, objective_metric,\n",
    "                                                n_days, S1_MIN_EVAL, S1_MIN_PRED1)\n",
    "                seed_scores.append(score)\n",
    "\n",
    "            mean_score = float(pd.Series(seed_scores).mean())\n",
    "            std_score  = float(pd.Series(seed_scores).std())\n",
    "            print(f'→ score={mean_score:.4f} (±{std_score:.4f})')\n",
    "\n",
    "            rows.append({\n",
    "                'n_days': n_days, 'threshold': threshold,\n",
    "                'score': mean_score, 'score_std': std_score,\n",
    "                **metrics, **_metrics_extra(metrics, n_days, pred_df),\n",
    "            })\n",
    "        except Exception as e:\n",
    "            print(f'→ ERROR: {e}')\n",
    "            rows.append({'n_days': n_days, 'threshold': threshold, 'score': 0.0, 'error': str(e)})\n",
    "\n",
    "    trials_df = pd.DataFrame(rows).sort_values('score', ascending=False).reset_index(drop=True)\n",
    "    best = trials_df.iloc[0]\n",
    "    return {\n",
    "        'trials_df': trials_df,\n",
    "        'best_n_days':    int(best['n_days']),\n",
    "        'best_threshold': float(best['threshold']),\n",
    "        'best_score':     float(best['score']),\n",
    "    }\n",
    "\n",
    "_s1_pkl = V4_CACHE / 'stage1_result.pkl'\n",
    "if LOAD_FROM_CACHE and _s1_pkl.exists():\n",
    "    stage1_result = load_cache('stage1_result', v4_only=True)\n",
    "else:\n",
    "    print('Stage 1 Grid Search 시작...')\n",
    "    stage1_result = run_stage1_grid_search(\n",
    "        objective_metric=S1_OBJ_METRIC, n_seeds=S1_N_SEEDS, random_state=RANDOM_STATE)\n",
    "    save_cache('stage1_result', stage1_result, v4_only=True)\n",
    "\n",
    "print(f'\\nStage 1 Best → n_days={stage1_result[\"best_n_days\"]}, '\n",
    "      f'threshold={stage1_result[\"best_threshold\"]}, score={stage1_result[\"best_score\"]:.4f}')\n",
    "stage1_result['trials_df'].to_csv(OUTPUT_DIR / 'stage1_grid_results.csv', index=False)\n",
    "display_df(stage1_result['trials_df'])\n",
])

C8 = code_cell([
    "def run_stage2_optuna(n_days, threshold, n_trials, objective_metric,\n",
    "                       precision_floor=0.65, random_state=42):\n",
    "    \"\"\"Stage 2: 모델+하이퍼파라미터 탐색. precision_hard 목표.\"\"\"\n",
    "    art    = build_feature_artifacts(n_days, threshold)\n",
    "    tc     = art['target_col']\n",
    "    ev     = art['all_lagged_eval_df']\n",
    "    all_fc = art['top_feature_cols_max']\n",
    "    rows   = []\n",
    "\n",
    "    def objective(trial):\n",
    "        top_n  = trial.suggest_int('top_n', S2_TOP_N_RANGE[0], min(S2_TOP_N_RANGE[1], len(all_fc)))\n",
    "        fc     = all_fc[:top_n]\n",
    "        mname  = trial.suggest_categorical('model_name', S2_MODELS)\n",
    "        mparams= suggest_model_params(trial, mname)\n",
    "        pth    = trial.suggest_float('pred_threshold',\n",
    "                                     S2_THRESH_RANGE[0], S2_THRESH_RANGE[1],\n",
    "                                     step=S2_THRESH_STEP)\n",
    "\n",
    "        tr_df = ev[(ev['Date']>=WINDOWS['train_start'])&(ev['Date']<=WINDOWS['train_end'])]\n",
    "        va_df = ev[(ev['Date']>=WINDOWS['optuna_valid_start'])&(ev['Date']<=WINDOWS['optuna_valid_end'])]\n",
    "\n",
    "        try:\n",
    "            _, metrics, pred_df = evaluate_model_on_period(\n",
    "                tr_df, va_df, fc, tc, close_col, n_days,\n",
    "                mname, mparams, pth, random_state=random_state)\n",
    "            score = compute_objective_score(\n",
    "                metrics, pred_df, objective_metric, n_days,\n",
    "                S2_MIN_EVAL, S2_MIN_PRED1, precision_floor=precision_floor)\n",
    "            row = {'trial': trial.number, 'score': score, 'model': mname,\n",
    "                   'top_n': top_n, 'pred_threshold': pth,\n",
    "                   **metrics, **_metrics_extra(metrics, n_days, pred_df),\n",
    "                   'model_params': json.dumps(mparams, default=str)}\n",
    "            rows.append(row)\n",
    "            trial.set_user_attr('model_params', mparams)\n",
    "            trial.set_user_attr('metrics', metrics)\n",
    "            return score\n",
    "        except Exception as e:\n",
    "            rows.append({'trial': trial.number, 'score': 0.0, 'error': str(e), 'model': mname})\n",
    "            return 0.0\n",
    "\n",
    "    study = optuna.create_study(direction='maximize')\n",
    "    study.optimize(objective, n_trials=n_trials)\n",
    "\n",
    "    trials_df = pd.DataFrame(rows).sort_values('score', ascending=False).reset_index(drop=True)\n",
    "    bt = study.best_trial\n",
    "\n",
    "    best_config = {\n",
    "        'n_days':           n_days,\n",
    "        'target_return_threshold': threshold,\n",
    "        'target_col':       art['target_col'],\n",
    "        'model_name':       bt.params['model_name'],\n",
    "        'model_params':     bt.user_attrs['model_params'],\n",
    "        'top_n':            bt.params['top_n'],\n",
    "        'pred_threshold':   bt.params['pred_threshold'],\n",
    "        'score':            bt.value,\n",
    "        'objective_metric': objective_metric,\n",
    "    }\n",
    "    return {'study': study, 'trials_df': trials_df, 'best_config': best_config, 'artifacts': art}\n",
    "\n",
    "_s2_pkl = V4_CACHE / 'stage2_result.pkl'\n",
    "if LOAD_FROM_CACHE and _s2_pkl.exists():\n",
    "    stage2_result = load_cache('stage2_result', v4_only=True)\n",
    "else:\n",
    "    print(f'Stage 2 Optuna 시작 ({S2_N_TRIALS} trials, objective={S2_OBJ_METRIC}) ...')\n",
    "    stage2_result = run_stage2_optuna(\n",
    "        stage1_result['best_n_days'], stage1_result['best_threshold'],\n",
    "        S2_N_TRIALS, S2_OBJ_METRIC, S2_PRECISION_FLOOR, RANDOM_STATE)\n",
    "    save_cache('stage2_result', stage2_result, v4_only=True)\n",
    "    save_cache('feature_cache', feature_cache)\n",
    "\n",
    "best_cfg = stage2_result['best_config']\n",
    "print('\\nBest config (Stage 2):')\n",
    "print(json.dumps(best_cfg, ensure_ascii=False, indent=2, default=str))\n",
    "stage2_result['trials_df'].to_csv(OUTPUT_DIR / 'stage2_optuna_trials.csv', index=False)\n",
    "display_df(stage2_result['trials_df'], 20)\n",
])

C9 = code_cell([
    "# ═══════════════════════════════════════════════════════════════════════\n",
    "# Stage 3 (v4 신규): Top-K 앙상블 + 검증셋 기반 precision threshold 보정\n",
    "# -----------------------------------------------------------------------\n",
    "# 1. Stage 2 trials 중 precision 상위 K개 설정으로 모델 재학습\n",
    "# 2. 검증셋에서 평균 앙상블 확률 계산\n",
    "# 3. precision >= 80% 달성하는 최소 임계값 탐색\n",
    "# 4. 해당 임계값 + 앙상블 모델을 시뮬레이션에 사용\n",
    "# ═══════════════════════════════════════════════════════════════════════\n",
    "\n",
    "def run_stage3_ensemble_calibration(\n",
    "        stage2_trials_df, art, best_cfg, windows, close_col,\n",
    "        precision_target=0.80, ensemble_top_k=5, min_pred=3, random_state=42):\n",
    "\n",
    "    tc     = art['target_col']\n",
    "    ev     = art['all_lagged_eval_df']\n",
    "    best_fc = art['top_feature_cols_max'][:best_cfg['top_n']]\n",
    "    n_days  = art['n_days']\n",
    "\n",
    "    tr_df = ev[(ev['Date']>=windows['train_start'])&(ev['Date']<=windows['train_end'])].copy()\n",
    "    va_df = ev[(ev['Date']>=windows['optuna_valid_start'])&(ev['Date']<=windows['optuna_valid_end'])].copy()\n",
    "\n",
    "    keep = [tc] + best_fc\n",
    "    tr_c  = tr_df[[c for c in keep if c in tr_df.columns]].replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "    va_c  = va_df[[c for c in ['Date', tc, f'future_ret_{n_days}d', close_col] + best_fc\n",
    "                   if c in va_df.columns]].replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "\n",
    "    X_tr = tr_c[best_fc]; y_tr = tr_c[tc].astype(int)\n",
    "    X_va = va_c[best_fc]; y_va = va_c[tc].astype(int).values\n",
    "\n",
    "    # Stage 2 trials에서 top-K 선별 (precision 순, 단 pred_1_count >= min_pred)\n",
    "    t2 = stage2_trials_df.copy()\n",
    "    t2 = t2[t2['pred_1_count'].fillna(0) >= min_pred]\n",
    "    t2 = t2.sort_values('precision', ascending=False).reset_index(drop=True)\n",
    "    top_k_df = t2.head(ensemble_top_k)\n",
    "    print(f'  앙상블 후보 {len(top_k_df)}개 (precision 기준):')\n",
    "    print(top_k_df[['trial','model','top_n','pred_threshold','precision','recall','pred_1_count']]\n",
    "          .to_string(index=False))\n",
    "\n",
    "    val_probas = []\n",
    "    ensemble_models = []\n",
    "\n",
    "    for _, row in top_k_df.iterrows():\n",
    "        try:\n",
    "            mname   = row['model']\n",
    "            raw_mp  = row.get('model_params', '{}')\n",
    "            mparams = json.loads(raw_mp) if isinstance(raw_mp, str) else (raw_mp or {})\n",
    "\n",
    "            # top_n이 best_fc와 다를 수 있으나 공통 feature set 사용\n",
    "            pos = int((y_tr==1).sum()); neg = int((y_tr==0).sum())\n",
    "            model = make_classifier(mname, random_state, mparams, pos, neg)\n",
    "            model.fit(X_tr, y_tr)\n",
    "\n",
    "            proba = model.predict_proba(X_va)[:,1]\n",
    "            val_probas.append(proba)\n",
    "            ensemble_models.append({'model': model, 'model_name': mname, 'trial_prec': float(row['precision'])})\n",
    "            print(f'    [{mname}] val_proba mean={proba.mean():.3f}')\n",
    "        except Exception as e:\n",
    "            print(f'    [SKIP] {row.get(\"model\",\"?\")} trial {row.get(\"trial\",\"?\")} : {e}')\n",
    "\n",
    "    if not val_probas:\n",
    "        raise ValueError('앙상블 모델 빌드 실패')\n",
    "\n",
    "    avg_proba = np.mean(val_probas, axis=0)\n",
    "\n",
    "    # 검증셋에서 precision >= target 달성하는 최저 임계값 탐색\n",
    "    found_th = found_prec = found_cnt = None\n",
    "    threshold_scan = []\n",
    "\n",
    "    for th in np.round(np.arange(0.99, 0.29, -0.01), 2):\n",
    "        pred = (avg_proba >= th).astype(int)\n",
    "        cnt  = int(pred.sum())\n",
    "        if cnt < min_pred:\n",
    "            threshold_scan.append({'threshold': th, 'precision': np.nan, 'pred_count': cnt})\n",
    "            continue\n",
    "        p = float(precision_score(y_va, pred, zero_division=0))\n",
    "        r = float(recall_score(y_va, pred, zero_division=0))\n",
    "        threshold_scan.append({'threshold': th, 'precision': p, 'recall': r, 'pred_count': cnt})\n",
    "        if found_th is None and p >= precision_target:\n",
    "            found_th, found_prec, found_cnt = float(th), p, cnt\n",
    "\n",
    "    scan_df = pd.DataFrame(threshold_scan)\n",
    "\n",
    "    if found_th is None:\n",
    "        # 목표 미달 → 최고 precision 선택\n",
    "        valid_scan = scan_df.dropna(subset=['precision'])\n",
    "        if not valid_scan.empty:\n",
    "            best_row   = valid_scan.loc[valid_scan['precision'].idxmax()]\n",
    "            found_th   = float(best_row['threshold'])\n",
    "            found_prec = float(best_row['precision'])\n",
    "            found_cnt  = int(best_row['pred_count'])\n",
    "        else:\n",
    "            found_th, found_prec, found_cnt = 0.5, 0.0, 0\n",
    "        print(f'  ⚠ precision {precision_target:.0%} 미달. 최고 precision: {found_prec:.3f} (threshold={found_th:.2f})')\n",
    "    else:\n",
    "        print(f'  ✓ precision {found_prec:.3f} @ threshold={found_th:.2f}  (pred_count={found_cnt}/{len(y_va)})')\n",
    "\n",
    "    return {\n",
    "        'ensemble_models': ensemble_models,\n",
    "        'feature_cols':    best_fc,\n",
    "        'calibrated_threshold': found_th,\n",
    "        'calibrated_val_precision': found_prec,\n",
    "        'calibrated_val_pred_count': found_cnt,\n",
    "        'val_avg_proba': avg_proba,\n",
    "        'y_val': y_va,\n",
    "        'val_df': va_c,\n",
    "        'scan_df': scan_df,\n",
    "        'n_ensemble': len(ensemble_models),\n",
    "    }\n",
    "\n",
    "\n",
    "best_artifacts = build_feature_artifacts(\n",
    "    best_cfg['n_days'], best_cfg['target_return_threshold'], include_infer_df=True)\n",
    "\n",
    "_s3_pkl = V4_CACHE / 'stage3_result.pkl'\n",
    "if LOAD_FROM_CACHE and _s3_pkl.exists():\n",
    "    stage3_result = load_cache('stage3_result', v4_only=True)\n",
    "else:\n",
    "    print('Stage 3 앙상블 보정 시작...')\n",
    "    stage3_result = run_stage3_ensemble_calibration(\n",
    "        stage2_trials_df=stage2_result['trials_df'],\n",
    "        art=best_artifacts,\n",
    "        best_cfg=best_cfg,\n",
    "        windows=WINDOWS,\n",
    "        close_col=close_col,\n",
    "        precision_target=S3_PRECISION_TARGET,\n",
    "        ensemble_top_k=S3_ENSEMBLE_TOP_K,\n",
    "        min_pred=S3_MIN_PRED,\n",
    "        random_state=RANDOM_STATE,\n",
    "    )\n",
    "    save_cache('stage3_result', stage3_result, v4_only=True)\n",
    "\n",
    "CALIBRATED_TH = stage3_result['calibrated_threshold']\n",
    "N_DAYS_BEST   = int(best_cfg['n_days'])\n",
    "target_col    = best_artifacts['target_col']\n",
    "all_lagged_ev = best_artifacts['all_lagged_eval_df']\n",
    "all_lagged_in = best_artifacts['all_lagged_infer_df']\n",
    "best_fc       = stage3_result['feature_cols']\n",
    "\n",
    "print(f'\\n★ 최종 설정:')\n",
    "print(f'  n_days={N_DAYS_BEST}, threshold={best_cfg[\"target_return_threshold\"]}')\n",
    "print(f'  앙상블 모델 수: {stage3_result[\"n_ensemble\"]}')\n",
    "print(f'  보정 임계값: {CALIBRATED_TH:.2f}')\n",
    "print(f'  검증 precision: {stage3_result[\"calibrated_val_precision\"]:.4f}')\n",
    "\n",
    "print('\\n[임계값별 검증 precision]')\n",
    "display_df(stage3_result['scan_df'].dropna(subset=['precision']), 30)\n",
])

C10 = code_cell([
    "# ── 앙상블로 시뮬레이션 테스트 예측 생성 ──────────────────────────────────\n",
    "def ensemble_predict_on_df(test_df, ensemble_models, feature_cols, threshold,\n",
    "                            target_col, close_col, n_days):\n",
    "    \"\"\"앙상블 확률 평균 → threshold 적용 → pred 생성\"\"\"\n",
    "    keep = [c for c in ['Date', target_col, f'future_ret_{n_days}d', close_col] + feature_cols\n",
    "            if c in test_df.columns]\n",
    "    ev = test_df[keep].replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "    if len(ev) == 0:\n",
    "        return ev\n",
    "\n",
    "    X_ev = ev[feature_cols]\n",
    "    probas = [m['model'].predict_proba(X_ev)[:,1] for m in ensemble_models]\n",
    "    avg_proba = np.mean(probas, axis=0)\n",
    "\n",
    "    ev['pred_proba'] = avg_proba\n",
    "    ev['pred']       = (avg_proba >= threshold).astype(int)\n",
    "    return ev\n",
    "\n",
    "\n",
    "# 시뮬레이션 훈련: train_start ~ optuna_valid_end (누수 없음)\n",
    "# 앙상블 각 모델을 train+valid 전체로 재학습\n",
    "tr_va_df = all_lagged_ev[\n",
    "    (all_lagged_ev['Date'] >= WINDOWS['train_start']) &\n",
    "    (all_lagged_ev['Date'] <= WINDOWS['optuna_valid_end'])\n",
    "].copy()\n",
    "\n",
    "sim_test_df = all_lagged_ev[\n",
    "    (all_lagged_ev['Date'] >= WINDOWS['sim_test_start']) &\n",
    "    (all_lagged_ev['Date'] <= WINDOWS['sim_test_end'])\n",
    "].copy()\n",
    "\n",
    "# train+valid 로 앙상블 재학습\n",
    "keep_trva = [target_col] + best_fc\n",
    "tr_va_c   = tr_va_df[[c for c in keep_trva if c in tr_va_df.columns]]\\\n",
    "             .replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "X_trva = tr_va_c[best_fc]; y_trva = tr_va_c[target_col].astype(int)\n",
    "pos_trva = int((y_trva==1).sum()); neg_trva = int((y_trva==0).sum())\n",
    "\n",
    "sim_ensemble_models = []\n",
    "for info in stage3_result['ensemble_models']:\n",
    "    mname   = info['model_name']\n",
    "    mparams = info['model'].get_params()  # 기존 모델의 파라미터 재사용\n",
    "    # 재학습\n",
    "    new_model = make_classifier(mname, RANDOM_STATE, mparams, pos_trva, neg_trva)\n",
    "    new_model.fit(X_trva, y_trva)\n",
    "    sim_ensemble_models.append({'model': new_model, 'model_name': mname})\n",
    "    print(f'  [{mname}] 재학습 완료')\n",
    "\n",
    "# 시뮬레이션 예측\n",
    "sim_pred_df = ensemble_predict_on_df(\n",
    "    sim_test_df, sim_ensemble_models, best_fc, CALIBRATED_TH,\n",
    "    target_col, close_col, N_DAYS_BEST)\n",
    "\n",
    "sim_metrics = safe_binary_metrics(\n",
    "    sim_pred_df[target_col].astype(int),\n",
    "    sim_pred_df['pred'].astype(int),\n",
    "    sim_pred_df['pred_proba'])\n",
    "\n",
    "print('\\n[Simulation Test 지표]')\n",
    "for k, v in sim_metrics.items():\n",
    "    print(f'  {k:20s}: {v}')\n",
    "\n",
    "prec_test = sim_metrics.get('precision', 0)\n",
    "flag = '✓' if prec_test >= 0.80 else '△' if prec_test >= 0.65 else '✗'\n",
    "print(f'\\n{flag} 시뮬레이션 테스트 precision: {prec_test:.4f}  (목표: 0.80)')\n",
])

C11 = code_cell([
    "def summarize_sim(pred_df, target_col, n_days):\n",
    "    ev = pred_df.dropna(subset=[target_col, 'pred', f'future_ret_{n_days}d']).copy()\n",
    "    if len(ev) == 0:\n",
    "        return pd.DataFrame([{'eval_count': 0}])\n",
    "    metrics = safe_binary_metrics(ev[target_col].astype(int), ev['pred'].astype(int), ev['pred_proba'])\n",
    "    ex      = _metrics_extra(metrics, n_days, ev)\n",
    "    strat   = np.where(ev['pred']==1, ev[f'future_ret_{n_days}d'], 0.0)\n",
    "    strat_if= np.where(ev[target_col].astype(int)==1, ev[f'future_ret_{n_days}d'], 0.0)\n",
    "    cret    = float(np.prod(1+strat)-1)\n",
    "    cret_if = float(np.prod(1+strat_if)-1)\n",
    "    avg_buy = float(ev.loc[ev['pred']==1, f'future_ret_{n_days}d'].mean()) if (ev['pred']==1).any() else np.nan\n",
    "    return pd.DataFrame([{'target_col': target_col, 'n_days': n_days,\n",
    "                           **metrics, **ex,\n",
    "                           'strategy_compound_return': cret,\n",
    "                           'strategy_compound_return_if': cret_if,\n",
    "                           'avg_ret_when_buy': avg_buy}])\n",
    "\n",
    "\n",
    "def make_cash_simulation(pred_df, close_col, target_col, n_days, take_profit_threshold,\n",
    "                          initial_cash=1_000_000, buy_ratio=0.05, min_cash_ratio=0.30):\n",
    "    df = pred_df.copy().sort_values('Date').reset_index(drop=True)\n",
    "    min_cash = initial_cash * min_cash_ratio\n",
    "    cash    = float(initial_cash); cash_if = float(initial_cash)\n",
    "    open_lots = []; open_lots_if = []\n",
    "    records   = []\n",
    "\n",
    "    def _process_lots(lots, price, i, tp_th):\n",
    "        remaining, sell_amt, reason = [], 0.0, None\n",
    "        for lot in lots:\n",
    "            ret = price / lot['buy_price'] - 1\n",
    "            if ret >= tp_th:\n",
    "                sell_amt += lot['qty'] * price; reason = 'TAKE_PROFIT'\n",
    "            elif lot['sell_idx'] <= i:\n",
    "                sell_amt += lot['qty'] * price\n",
    "                if reason != 'TAKE_PROFIT': reason = 'EXPIRE'\n",
    "            else:\n",
    "                remaining.append(lot)\n",
    "        return remaining, sell_amt, reason\n",
    "\n",
    "    def _buy(lots, cash_val, asset_val, price, i, buy_ratio, min_cash):\n",
    "        spend = min(asset_val * buy_ratio, cash_val - min_cash)\n",
    "        if spend <= 0 or price <= 0: return lots, cash_val, 0.0\n",
    "        qty = spend / price; cash_val -= spend\n",
    "        lots.append({'buy_price': price, 'qty': qty, 'sell_idx': i + n_days})\n",
    "        return lots, cash_val, spend\n",
    "\n",
    "    for i, row in df.iterrows():\n",
    "        date   = row['Date']; price = float(row[close_col])\n",
    "        actual = int(row[target_col]) if pd.notna(row.get(target_col)) else 0\n",
    "\n",
    "        open_lots, sell_amt, sell_rsn = _process_lots(open_lots, price, i, take_profit_threshold)\n",
    "        cash += sell_amt\n",
    "        holding = sum(l['qty']*price for l in open_lots)\n",
    "        asset   = cash + holding\n",
    "        action  = 'HOLD'; buy_amt = 0.0\n",
    "        if pd.notna(row.get('pred')) and int(row['pred']) == 1 and cash > min_cash:\n",
    "            open_lots, cash, buy_amt = _buy(open_lots, cash, asset, price, i, buy_ratio, min_cash)\n",
    "            action = 'BUY'\n",
    "        if sell_amt > 0: action = f'SELL_{sell_rsn}' + ('_BUY' if buy_amt > 0 else '')\n",
    "        holding = sum(l['qty']*price for l in open_lots)\n",
    "        asset   = cash + holding\n",
    "\n",
    "        open_lots_if, sell_amt_if, sell_rsn_if = _process_lots(open_lots_if, price, i, take_profit_threshold)\n",
    "        cash_if += sell_amt_if\n",
    "        holding_if = sum(l['qty']*price for l in open_lots_if)\n",
    "        asset_if   = cash_if + holding_if\n",
    "        action_if  = 'HOLD'; buy_amt_if = 0.0\n",
    "        if actual == 1 and cash_if > min_cash:\n",
    "            open_lots_if, cash_if, buy_amt_if = _buy(open_lots_if, cash_if, asset_if, price, i, buy_ratio, min_cash)\n",
    "            action_if = 'BUY'\n",
    "        if sell_amt_if > 0: action_if = f'SELL_{sell_rsn_if}' + ('_BUY' if buy_amt_if > 0 else '')\n",
    "        holding_if = sum(l['qty']*price for l in open_lots_if)\n",
    "        asset_if   = cash_if + holding_if\n",
    "\n",
    "        records.append({'Date': date, 'price': price,\n",
    "                        'pred': row.get('pred'), 'pred_proba': row.get('pred_proba'),\n",
    "                        'actual_target': actual,\n",
    "                        'trade_action': action, 'cash': cash, 'buy_amount': buy_amt,\n",
    "                        'sell_amount': sell_amt, 'holding_value': holding, 'asset': asset,\n",
    "                        'cum_return': asset / initial_cash - 1,\n",
    "                        'trade_action_if': action_if, 'cash_if': cash_if,\n",
    "                        'buy_amount_if': buy_amt_if, 'sell_amount_if': sell_amt_if,\n",
    "                        'holding_value_if': holding_if, 'asset_if': asset_if,\n",
    "                        'cum_return_if': asset_if / initial_cash - 1})\n",
    "    return pd.DataFrame(records)\n",
    "\n",
    "\n",
    "sim_summary_df   = summarize_sim(sim_pred_df, target_col, N_DAYS_BEST)\n",
    "take_profit_th   = best_cfg['target_return_threshold']\n",
    "cash_sim_df      = make_cash_simulation(\n",
    "    sim_pred_df, close_col, target_col, N_DAYS_BEST,\n",
    "    take_profit_threshold=take_profit_th,\n",
    "    initial_cash=INITIAL_CASH, buy_ratio=BUY_RATIO, min_cash_ratio=MIN_CASH_RATIO)\n",
    "\n",
    "print('[Simulation Test 요약]')\n",
    "display_df(sim_summary_df.T.rename(columns={0:'value'}))\n",
    "print()\n",
    "print('pred 기준 action 분포:')\n",
    "print(cash_sim_df['trade_action'].value_counts(dropna=False))\n",
    "\n",
    "final_asset    = cash_sim_df['asset'].iloc[-1]\n",
    "final_asset_if = cash_sim_df['asset_if'].iloc[-1]\n",
    "print(f'\\n최종 자산 (pred 기준): {final_asset:,.0f}  ({(final_asset/INITIAL_CASH-1)*100:.1f}%)')\n",
    "print(f'최종 자산 (what-if):   {final_asset_if:,.0f}  ({(final_asset_if/INITIAL_CASH-1)*100:.1f}%)')\n",
])

C12 = code_cell([
    "# ── 그래프 1: pred vs actual_target ───────────────────────────────────────\n",
    "fig_pred_actual = go.Figure()\n",
    "fig_pred_actual.add_trace(go.Scatter(\n",
    "    x=sim_pred_df['Date'], y=sim_pred_df['pred'].astype(float) + 0.04,\n",
    "    mode='lines+markers', name='pred (앙상블 신호)',\n",
    "    line=dict(width=2, dash='dot'), marker=dict(size=7, symbol='x')))\n",
    "fig_pred_actual.add_trace(go.Scatter(\n",
    "    x=sim_pred_df['Date'], y=sim_pred_df[target_col].astype(float),\n",
    "    mode='lines+markers', name='actual_target',\n",
    "    line=dict(width=2), marker=dict(size=7, symbol='circle')))\n",
    "fig_pred_actual.update_layout(\n",
    "    title=f'{ETF_CODE} v4 — pred vs actual_target (precision={sim_metrics.get(\"precision\",0):.3f})',\n",
    "    xaxis_title='Date', yaxis_title='0 / 1', hovermode='x unified', height=420,\n",
    "    yaxis=dict(tickvals=[0,1], ticktext=['0','1'], range=[-0.2,1.4]))\n",
    "fig_pred_actual.show()\n",
    "\n",
    "# ── 그래프 2: 자산 추이 ────────────────────────────────────────────────────\n",
    "fig_cash_flow = go.Figure()\n",
    "fig_cash_flow.add_trace(go.Scatter(\n",
    "    x=cash_sim_df['Date'], y=cash_sim_df['asset'],\n",
    "    mode='lines', name='자산 (앙상블 pred)', line=dict(width=2)))\n",
    "fig_cash_flow.add_trace(go.Scatter(\n",
    "    x=cash_sim_df['Date'], y=cash_sim_df['asset_if'],\n",
    "    mode='lines', name='자산 (what-if)', line=dict(width=2, dash='dash')))\n",
    "fig_cash_flow.add_hline(y=INITIAL_CASH, line_dash='dot', line_color='gray',\n",
    "    annotation_text='초기자산', annotation_position='bottom right')\n",
    "fig_cash_flow.update_layout(\n",
    "    title=f'{ETF_CODE} v4 — 자산 추이',\n",
    "    xaxis_title='Date', yaxis_title='자산 (KRW)', hovermode='x unified', height=420)\n",
    "fig_cash_flow.show()\n",
    "\n",
    "# ── 그래프 3: threshold scan ───────────────────────────────────────────────\n",
    "scan_valid = stage3_result['scan_df'].dropna(subset=['precision'])\n",
    "if not scan_valid.empty:\n",
    "    fig_scan = go.Figure()\n",
    "    fig_scan.add_trace(go.Scatter(\n",
    "        x=scan_valid['threshold'], y=scan_valid['precision'],\n",
    "        mode='lines+markers', name='validation precision'))\n",
    "    if 'recall' in scan_valid.columns:\n",
    "        fig_scan.add_trace(go.Scatter(\n",
    "            x=scan_valid['threshold'], y=scan_valid['recall'],\n",
    "            mode='lines', name='validation recall', line=dict(dash='dot')))\n",
    "    fig_scan.add_hline(y=S3_PRECISION_TARGET, line_dash='dash', line_color='red',\n",
    "        annotation_text=f'목표 {S3_PRECISION_TARGET:.0%}')\n",
    "    fig_scan.add_vline(x=CALIBRATED_TH, line_dash='dot', line_color='green',\n",
    "        annotation_text=f'선택 th={CALIBRATED_TH:.2f}')\n",
    "    fig_scan.update_layout(\n",
    "        title='Stage 3 — Threshold Scan (검증셋 precision/recall)',\n",
    "        xaxis_title='threshold', yaxis_title='metric', height=400)\n",
    "    fig_scan.show()\n",
])

C13 = code_cell([
    "# BASE_DATE까지 전체 데이터로 앙상블 재학습 → 최신 신호 추론\n",
    "final_train_df = all_lagged_ev[all_lagged_ev['Date'] <= WINDOWS['base_date']].copy()\n",
    "keep_fin = [target_col] + best_fc\n",
    "fin_c    = final_train_df[[c for c in keep_fin if c in final_train_df.columns]]\\\n",
    "           .replace([np.inf,-np.inf], np.nan).dropna().copy()\n",
    "X_fin = fin_c[best_fc]; y_fin = fin_c[target_col].astype(int)\n",
    "pos_fin = int((y_fin==1).sum()); neg_fin = int((y_fin==0).sum())\n",
    "\n",
    "final_ensemble = []\n",
    "for info in stage3_result['ensemble_models']:\n",
    "    mname   = info['model_name']\n",
    "    mparams = info['model'].get_params()\n",
    "    m = make_classifier(mname, RANDOM_STATE, mparams, pos_fin, neg_fin)\n",
    "    m.fit(X_fin, y_fin)\n",
    "    final_ensemble.append(m)\n",
    "\n",
    "latest_row    = all_lagged_in.iloc[[-1]].copy()\n",
    "latest_date   = latest_row['Date'].values[0]\n",
    "X_latest      = latest_row[best_fc].replace([np.inf,-np.inf], np.nan)\n",
    "\n",
    "final_probas  = [m.predict_proba(X_latest)[:,1][0] for m in final_ensemble]\n",
    "avg_proba_lat = float(np.mean(final_probas))\n",
    "pred_latest   = int(avg_proba_lat >= CALIBRATED_TH)\n",
    "\n",
    "real_inference = {\n",
    "    'as_of_date':     str(latest_date)[:10],\n",
    "    'base_date':      BASE_DATE,\n",
    "    'n_days':         N_DAYS_BEST,\n",
    "    'target_col':     target_col,\n",
    "    'ensemble_count': len(final_ensemble),\n",
    "    'individual_probas': [round(p, 4) for p in final_probas],\n",
    "    'avg_pred_proba': round(avg_proba_lat, 4),\n",
    "    'calibrated_threshold': CALIBRATED_TH,\n",
    "    'signal':         'BUY' if pred_latest == 1 else 'WAIT',\n",
    "}\n",
    "print(json.dumps(real_inference, ensure_ascii=False, indent=2))\n",
])

C14 = code_cell([
    "base_tag = f\"{ETF_CODE}_{pd.to_datetime(BASE_DATE).strftime('%Y%m%d')}\"\n",
    "\n",
    "sim_pred_df.to_csv(OUTPUT_DIR / f'sim_pred_{base_tag}.csv', index=False)\n",
    "cash_sim_df.to_csv(OUTPUT_DIR / f'cash_sim_{base_tag}.csv', index=False)\n",
    "best_artifacts['importance_df'].to_csv(OUTPUT_DIR / f'feature_importance_{base_tag}.csv', index=False)\n",
    "stage1_result['trials_df'].to_csv(OUTPUT_DIR / f'stage1_trials_{base_tag}.csv', index=False)\n",
    "stage2_result['trials_df'].to_csv(OUTPUT_DIR / f'stage2_trials_{base_tag}.csv', index=False)\n",
    "stage3_result['scan_df'].to_csv(OUTPUT_DIR / f'stage3_threshold_scan_{base_tag}.csv', index=False)\n",
    "\n",
    "with open(OUTPUT_DIR / f'best_config_{base_tag}.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(best_cfg, f, ensure_ascii=False, indent=2, default=str)\n",
    "with open(OUTPUT_DIR / f'real_inference_{base_tag}.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(real_inference, f, ensure_ascii=False, indent=2, default=str)\n",
    "\n",
    "fig_pred_actual.write_html(OUTPUT_DIR / f'plot_pred_vs_actual_{base_tag}.html')\n",
    "fig_cash_flow.write_html(OUTPUT_DIR / f'plot_cash_flow_{base_tag}.html')\n",
    "\n",
    "# 누적 summary CSV\n",
    "summary_path = Path('experiments_v4/experiment_summary_v4.csv')\n",
    "summary_path.parent.mkdir(parents=True, exist_ok=True)\n",
    "s1row = sim_summary_df.iloc[0].to_dict()\n",
    "summary_row = {\n",
    "    'experiment_name':          EXPERIMENT_NAME,\n",
    "    'run_date':                 pd.Timestamp.now().strftime('%Y-%m-%d %H:%M'),\n",
    "    'etf':                      ETF_CODE,\n",
    "    'base_date':                BASE_DATE,\n",
    "    'best_n_days':              best_cfg['n_days'],\n",
    "    'best_threshold':           best_cfg['target_return_threshold'],\n",
    "    'best_model_s2':            best_cfg['model_name'],\n",
    "    'ensemble_count':           stage3_result['n_ensemble'],\n",
    "    'calibrated_threshold':     CALIBRATED_TH,\n",
    "    'val_precision':            stage3_result['calibrated_val_precision'],\n",
    "    'val_pred_count':           stage3_result['calibrated_val_pred_count'],\n",
    "    'sim_precision':            s1row.get('precision'),\n",
    "    'sim_recall':               s1row.get('recall'),\n",
    "    'sim_f1':                   s1row.get('f1'),\n",
    "    'sim_pred_count':           s1row.get('pred_1_count'),\n",
    "    'sim_precision_lift':       s1row.get('precision_lift'),\n",
    "    'sim_compound_return':      s1row.get('strategy_compound_return'),\n",
    "    'sim_avg_ret_buy':          s1row.get('avg_ret_when_buy'),\n",
    "    'cash_sim_final_value':     cash_sim_df['asset'].iloc[-1],\n",
    "    'cash_sim_return_pct':      (cash_sim_df['asset'].iloc[-1] / INITIAL_CASH - 1) * 100,\n",
    "    'real_signal':              real_inference['signal'],\n",
    "    'real_pred_proba':          real_inference['avg_pred_proba'],\n",
    "    's2_n_trials':              S2_N_TRIALS,\n",
    "    'precision_floor':          S2_PRECISION_FLOOR,\n",
    "    'precision_target':         S3_PRECISION_TARGET,\n",
    "}\n",
    "\n",
    "if summary_path.exists():\n",
    "    new_df = pd.concat([pd.read_csv(summary_path), pd.DataFrame([summary_row])], ignore_index=True)\n",
    "else:\n",
    "    new_df = pd.DataFrame([summary_row])\n",
    "new_df.to_csv(summary_path, index=False)\n",
    "\n",
    "print(f'결과 저장 완료: {OUTPUT_DIR.resolve()}')\n",
    "print(f'Summary CSV: {summary_path.resolve()}')\n",
    "display_df(new_df)\n",
])

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": [C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14]
}

out = "ETF_oos_simulation_v4.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"✓ {out} 생성 완료  (셀 수: {len(notebook['cells'])})")
